name: CI
on: [push]
jobs:
  golang-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Lint code
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
  golang-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Download dependencies
        run: go mod download
        
      - name: Run tests
        run: go test -v ./...


