name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Start MongoDB
        run: docker run -d -p 27017:27017 --name mongo  mongo:6.0 --replSet test --bind_ip_all

      - name: Initialize MongoDB Replica Set
        run: |
          sleep 10
          docker run --rm mongo:6.0 mongosh --host 172.17.0.1 --eval 'rs.initiate({_id: "test", members: [{_id: 0, host: "172.17.0.1:27017"}]})'

          
      - name: Install MongoDB Shell
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Verify replica set health
        run: ./scripts/verify-mongo-health.sh

      - name: Download Go dependencies
        run: go mod download
        
      - name: Run tests
        run: go test -v ./...

      - name: Stop MongoDB
        if: always()
        run: docker compose down