name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Start MongoDB
        run: |
          docker compose up -d
          # Wait for MongoDB container to be ready
          while ! docker compose ps mongodb | grep -q "healthy"; do
            echo "Waiting for MongoDB to be healthy..."
            sleep 5
          done

      - name: Install MongoDB Shell
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Initialize MongoDB Replica Set
        run: ./scripts/init-mongo.sh

      - name: Download Go dependencies
        run: go mod download
        
      - name: Run tests
        run: go test -v ./...

      - name: Stop MongoDB
        if: always()
        run: docker compose down